name: Healthcheck

on:
  workflow_dispatch:
  schedule:
    - cron: '0/10 * * * *'

jobs:
  healthcheck:
    runs-on: ${{ vars.RUNNER }}
    env:
      SERVER_URL: ${{ vars.SERVER_URL }}
    steps:
      - run: echo "pinging ${{ env.SERVER_URL }}/health"
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: "${{ env.SERVER_URL }}/health"
          max-attempts: 3
          retry-delay: 5s