name: Hello World!

on: push

jobs:
    hello_world:
        runs-on: ubuntu-20.04
        name: Greet the World
        steps:
            - run: echo "Hello World!"
            - name: Current Date
              run: date
            - name: Directory Contents
              run: ls -l