name: Deployment pipeline

on:
  push:
    branches:
      - main

env:
    RUNNER: ubuntu-20.04
    NODE_VERSION: '20'
    CHECKOUT: actions/checkout@v4
    SETUP_NODE: actions/setup-node@v4

jobs:
  simple_deployment_pipeline:
    runs-on: $RUNNER
    steps:
      - uses: $CHECKOUT
      - uses: $SETUP_NODE
        with:
          node-version: NODE_VERSION
      - name: Install dependencies 
        run: npm install  
      - name: Check style
        run: npm run eslint
      - name: Run unit tests
        run: npm run test
        # Playwright End-To-End tests
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright End-To-End tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Build
        run: npm run build
  deploy_to_render:
    needs: simple_deployment_pipeline
    # only deploy if the above checks pass
    if: ${{ success() }}
    runs-on: $RUNNER
    steps:
      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: curl "$deploy_url"
