name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  simple_deployment_pipeline:
    runs-on: ${{ vars.RUNNER }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
      - name: Install dependencies 
        run: npm install  
      - name: Check style
        run: npm run eslint
      - name: Run unit tests
        run: npm run test
        # Playwright End-To-End tests
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright End-To-End tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Build
        run: npm run build
  bump_version_tag:
    needs: simple_deployment_pipeline
    # only deploy if the above checks pass and is a push
    if: ${{ success() && github.event_name == 'push' }}
    runs-on: ${{ vars.RUNNER }}
    steps:
      - name: Bump version tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      
  deploy_to_render:
    # probably not particularly necessary to have the tagging
    # succeed, but it's nice to have the repo in a "consistent"
    # state before deployment
    needs: [simple_deployment_pipeline, bump_version_tag]
    # only deploy if the above checks pass and is a push
    if: ${{ success() && github.event_name == 'push' }}
    runs-on: ${{ vars.RUNNER }}
    steps:
      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: curl "$deploy_url"
