name: Testing

on: push

env:
  DUMMY_TRUE: ${{ true }}
  TEST_VAR: ${{ contains(join(github.event.commits.*.message), '#skip') }}

jobs:
  test:
    runs-on: ${{ vars.RUNNER }}
    steps:
      - name: test
        run: echo "testing"
      - name: env
        run: echo "skip deploy $TEST_VAR"
  not-skipped-test:
    runs-on: ${{ vars.RUNNER }}
    if: ${{ github.env.DUMMY_TRUE }}
    steps:
      - run: echo "Should be run"

  test-contains:
    runs-on: ${{ vars.RUNNER }}
    steps:
      - if: ${{ env.TEST_VAR }}
        run: echo "contained skip"
      - if: ${{ env.DUMMY_TRUE }}
        run: echo "always run"